In [1]:
import numpy as np
import pandas as pd

In [3]:
rd=pd.read_csv('train.csv')

In [4]:
rd

Date stations observation     0     1     2     3     4     5  \
0       2014/1/1  station    AMB_TEMP    14    14    14    13    12    12   
1       2014/1/1  station         CH4   1.8   1.8   1.8   1.8   1.8   1.8   
2       2014/1/1  station          CO  0.51  0.41  0.39  0.37  0.35   0.3   
3       2014/1/1  station        NMHC   0.2  0.15  0.13  0.12  0.11  0.06   
4       2014/1/1  station          NO   0.9   0.6   0.5   1.7   1.8   1.5   
5       2014/1/1  station         NO2    16   9.2   8.2   6.9   6.8   3.8   
6       2014/1/1  station         NOx    17   9.8   8.7   8.6   8.5   5.3   
7       2014/1/1  station          O3    16    30    27    23    24    28   
8       2014/1/1  station        PM10    56    50    48    35    25    12   
9       2014/1/1  station       PM2.5    26    39    36    35    31    28   
10      2014/1/1  station    RAINFALL    NR    NR    NR    NR    NR    NR   
11      2014/1/1  station          RH    77    68    67    74    72    73   
12      2014/1/1  station         SO2   1.8     2   1.7   1.6   1.9   1.4   
13      2014/1/1  station         THC     2     2     2   1.9   1.9   1.8   
14      2014/1/1  station       WD_HR    37    80    57    76   110   106   
15      2014/1/1  station  WIND_DIREC    35    79   2.4    55    94   116   
16      2014/1/1  station  WIND_SPEED   1.4   1.8     1   0.6   1.7   2.5   
17      2014/1/1  station       WS_HR   0.5   0.9   0.6   0.3   0.6   1.9   
18      2014/1/2  station    AMB_TEMP    16    15    15    14    14    15   
19      2014/1/2  station         CH4   1.8   1.8   1.8   1.8   1.8   1.8   
20      2014/1/2  station          CO  0.26  0.25  0.28  0.27  0.24  0.26   
21      2014/1/2  station        NMHC  0.06  0.05  0.06  0.05  0.05  0.07   
22      2014/1/2  station          NO   1.4   1.1   1.3     1   1.2   1.1   
23      2014/1/2  station         NO2   3.7   3.2   3.3   3.1   3.1   4.3   
24      2014/1/2  station         NOx     5   4.3   4.7   4.1   4.3   5.5   
25      2014/1/2  station          O3    39    38    39    39    34    31   
26      2014/1/2  station        PM10    49    34    31    16    18     8   
27      2014/1/2  station       PM2.5    21    23    30    30    22    18   
28      2014/1/2  station    RAINFALL    NR    NR    NR    NR    NR    NR   
29      2014/1/2  station          RH    65    66    70    71    70    67   
...          ...      ...         ...   ...   ...   ...   ...   ...   ...   
4290  2014/12/19  station         NOx   8.8   7.5   8.5   8.2   8.6   9.3   
4291  2014/12/19  station          O3    30    33    30    34    37    36   
4292  2014/12/19  station        PM10    45    50    64    51    44    34   
4293  2014/12/19  station       PM2.5    14    16    13    14    21    19   
4294  2014/12/19  station    RAINFALL    NR    NR    NR    NR    NR    NR   
4295  2014/12/19  station          RH    71    70    71    70    70    71   
4296  2014/12/19  station         SO2  -0.2     2   2.1   2.2   2.3   2.5   
4297  2014/12/19  station         THC   1.9   1.9     2   1.9   1.9     2   
4298  2014/12/19  station       WD_HR   115   119   102   119    97    90   
4299  2014/12/19  station  WIND_DIREC   118   119   110   123   111    86   
4300  2014/12/19  station  WIND_SPEED   1.8   1.7   1.8     2   1.6   1.4   
4301  2014/12/19  station       WS_HR   1.5   1.4   1.3   1.9   1.3     1   
4302  2014/12/20  station    AMB_TEMP    14    14    14    14    14    14   
4303  2014/12/20  station         CH4   1.7   1.7   1.7   1.7   1.7   1.7   
4304  2014/12/20  station          CO  0.21   0.2  0.17  0.17  0.16  0.14   
4305  2014/12/20  station        NMHC  0.06  0.09  0.05  0.06  0.05  0.04   
4306  2014/12/20  station          NO   1.4   1.6   1.3   0.3   0.3   0.5   
4307  2014/12/20  station         NO2   8.5   8.7   4.1   6.3   4.3     4   
4308  2014/12/20  station         NOx   9.9    10   5.4   6.6   4.6   4.5   
4309  2014/12/20  station          O3    23    22    32    30    32    32   
4310  20

In [5]:
rd1=rd[rd['observation']=='PM2.5']

In [6]:
rd1

Date stations observation   0   1   2   3   4   5   6 ...  14  15  \
9       2014/1/1  station       PM2.5  26  39  36  35  31  28  25 ...  36  45   
27      2014/1/2  station       PM2.5  21  23  30  30  22  18  13 ...  53  43   
45      2014/1/3  station       PM2.5  19  25  27  20  16  14  15 ...  32  36   
63      2014/1/4  station       PM2.5  27  27  14  20  22  24  26 ...  62  55   
81      2014/1/5  station       PM2.5  80  80  76  81  75  66  70 ...  64  73   
99      2014/1/6  station       PM2.5  66  55  46  46  46  42  35 ...  62  59   
117     2014/1/7  station       PM2.5  41  32  35  31  33  25  36 ...  62  61   
135     2014/1/8  station       PM2.5  48  53  60  60  52  47  45 ...  35  36   
153     2014/1/9  station       PM2.5  18  15   9   9  14  15  20 ...  20  20   
171    2014/1/10  station       PM2.5   6   7   7   0   0   1   1 ...  23  20   
189    2014/1/11  station       PM2.5  25  21  25  24  23  18  20 ...  36  36   
207    2014/1/12  station       PM2.5  48  56  62  52  40  32  37 ...  19  24   
225    2014/1/13  station       PM2.5  10  10  10  13  18  16   7 ...  18  29   
243    2014/1/14  station       PM2.5  29  23  21  21  30  26  26 ...  10   6   
261    2014/1/15  station       PM2.5   9   4   8   5  14  11  13 ...   4  13   
279    2014/1/16  station       PM2.5  24  16   7   7   6   5   2 ...  30  41   
297    2014/1/17  station       PM2.5  27  25  22  23  22  22  23 ...  16  20   
315    2014/1/18  station       PM2.5  17  26  25  24  10   7  11 ...  81  90   
333    2014/1/19  station       PM2.5  64  52  36  41  46  48  38 ...  50  57   
351    2014/1/20  station       PM2.5  61  59  60  48  53  60  66 ...  51  47   
369     2014/2/1  station       PM2.5  30  32  36  29  16  10  23 ...  21  19   
387     2014/2/2  station       PM2.5  22  20  13   8  15  13  22 ...  33  28   
405     2014/2/3  station       PM2.5  31  26  17  13  18  29  22 ...  30  32   
423     2014/2/4  station       PM2.5  22  27  22  31  32  35  25 ...   8  12   
441     2014/2/5  station       PM2.5   6   6   4   4   0   0   0 ...  28  36   
459     2014/2/6  station       PM2.5  13  22  29  21  21  14  16 ...  29  29   
477     2014/2/7  station       PM2.5  46  44  38  36  23  19   7 ...  24  25   
495     2014/2/8  station       PM2.5  32  35  25  13  12   7   7 ...   7  15   
513     2014/2/9  station       PM2.5   4   6   0   0   0   7   7 ...  11  12   
531    2014/2/10  station       PM2.5   0   0   4   4   8   9  13 ...   3  11   
...          ...      ...         ...  ..  ..  ..  ..  ..  ..  .. ...  ..  ..   
3789  2014/11/11  station       PM2.5  11   6  14  12  12   0   2 ...  39  32   
3807  2014/11/12  station       PM2.5  21  16  26  18  11   6   7 ...  18  30   
3825  2014/11/13  station       PM2.5  14  11  14  14  10   4   9 ...  16  26   
3843  2014/11/14  station       PM2.5   9   6   6   5   0   4   7 ...   6   3   
3861  2014/11/15  station       PM2.5   9   4   6   1   1   0   0 ...  34  54   
3879  2014/11/16  station       PM2.5   0   0   0   0   1   1  13 ...  18  18   
3897  2014/11/17  station       PM2.5  -1  -1  -1  -1  -1  -1  -1 ...  19  19   
3915  2014/11/18  station       PM2.5   6  12  11  11   7   3  13 ...  22  22   
3933  2014/11/19  station       PM2.5   9   3   0   4   4   8   2 ...  71  69   
3951  2014/11/20  station       PM2.5  10   8   8   2   2   0   4 ...  26  26   
3969   2014/12/1  station       PM2.5  22  17  17  22  27  26   9 ...   1  18   
3987   2014/12/2  station       PM2.5  14   6   0  10  15  24  15 ...  12   4   
4005   2014/12/3  station       PM2.5  20   5  12  15  22  14   6 ...  32  38   
4023   2014/12/4  station       PM2.5  21  21  21   0   0   0   0 ...   0  10   
4041   2014/12/5  station       PM2.5  20  20  20  20  20  21  29 ...  13  11   
4059   2014/12/6  station       PM2.5   7   2   0   0   1   5   9 ...  15  16   
4077   2014/12/7  station       PM2.5   8   6  19  21  20   4   0 ...  34  35   
4095   2014/12/8  station       PM2.5  27  

In [7]:
rd2=rd1.iloc[:,3:]
rd2

0   1   2   3   4   5   6   7   8   9 ...  14  15   16   17   18   19  \
9     26  39  36  35  31  28  25  20  19  30 ...  36  45   42   49   45   44   
27    21  23  30  30  22  18  13  13  11  22 ...  53  43   43   45   46   32   
45    19  25  27  20  16  14  15   8   4   9 ...  32  36   34   45   40   41   
63    27  27  14  20  22  24  26  33  48  50 ...  62  55   56   67   78   83   
81    80  80  76  81  75  66  70  65  66  57 ...  64  73   57   57   53   70   
99    66  55  46  46  46  42  35  35  40  45 ...  62  59   61   50   60   62   
117   41  32  35  31  33  25  36  28  33  29 ...  62  61   47   54   57   59   
135   48  53  60  60  52  47  45  50  43  40 ...  35  36   36   32   33   33   
153   18  15   9   9  14  15  20  16  23  16 ...  20  20   20   18   18   22   
171    6   7   7   0   0   1   1   7   7   8 ...  23  20   18   15   16   10   
189   25  21  25  24  23  18  20  14   7  17 ...  36  36   29   32   33   30   
207   48  56  62  52  40  32  37  31  34  32 ...  19  24   25   14   16   22   
225   10  10  10  13  18  16   7   5   2  11 ...  18  29   38   43   44   48   
243   29  23  21  21  30  26  26  26  23  16 ...  10   6    4    7   14   20   
261    9   4   8   5  14  11  13   4   9  15 ...   4  13   14   18   20   25   
279   24  16   7   7   6   5   2  17  15  33 ...  30  41   38   34   27   26   
297   27  25  22  23  22  22  23  11   2  18 ...  16  20   16   34   32   27   
315   17  26  25  24  10   7  11  16  19   9 ...  81  90  109  109  105  102   
333   64  52  36  41  46  48  38  21  11  11 ...  50  57   66   72   77   72   
351   61  59  60  48  53  60  66  53  55  57 ...  51  47   44   46   46   39   
369   30  32  36  29  16  10  23  27  33  21 ...  21  19   19   19   18   27   
387   22  20  13   8  15  13  22  19  23  15 ...  33  28   25   21   23   27   
405   31  26  17  13  18  29  22  21  23  34 ...  30  32   24   27   17   20   
423   22  27  22  31  32  35  25  14   7   0 ...   8  12   15   17    9   11   
441    6   6   4   4   0   0   0   2   2   2 ...  28  36   23   21   25   16   
459   13  22  29  21  21  14  16   6  11  10 ...  29  29   34   39   40   52   
477   46  44  38  36  23  19   7  21  20  25 ...  24  25   27   24   23   20   
495   32  35  25  13  12   7   7   6   7   9 ...   7  15   12    7    0    3   
513    4   6   0   0   0   7   7   5   7  10 ...  11  12   12    2    6    6   
531    0   0   4   4   8   9  13  10   4   0 ...   3  11    7   15    8   19   
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  .. ...  ..  ..  ...  ...  ...  ...   
3789  11   6  14  12  12   0   2   7  12  23 ...  39  32   17   19   27   41   
3807  21  16  26  18  11   6   7  12   4   6 ...  18  30   30   18   11   10   
3825  14  11  14  14  10   4   9  14  10  17 ...  16  26   33   33   37   26   
3843   9   6   6   5   0   4   7   9  12  14 ...   6   3    3   13   19   15   
3861   9   4   6   1   1   0   0   0   4   6 ...  34  54   69   66   59   36   
3879   0   0   0   0   1   1  13  19  23  14 ...  18  18   18   -1   -1   -1   
3897  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1 ...  19  19   19   12    3    6   
3915   6  12  11  11   7   3  13  31  47  47 ...  22  22   21   21   19   14   
3933   9   3   0   4   4   8   2   4   8  14 ...  71  69   38    9    9   14   
3951  10   8   8   2   2   0   4  14  25  20 ...  26  26   25   34   39   38   
3969  22  17  17  22  27  26   9   4   0   0 ...   1  18   30   33   15   10   
3987  14   6   0  10  15  24  15  14  14  21 ...  12   4   13   13   17    7   
4005  20   5  12  15  22  14   6   4  13  20 ...  32  38   36   35   27   24   
4023  21  21  21   0   0   0   0   0   0   0 ...   0  10   18   18   18   18   
4041  20  20  20  20  20  21  29  29  27  21 ...  13  11   18   28   33   37   
4059   7   2   0   0   1   5   9   8   2   1 ...  15  16   22   25   27   18   
4077   8   6  19  21  20   4   0   0   0   3 ...  34  35   36   40   31   35   
4095  27  15  11  11  14  15  15  17  23  24 ...   7  12   15   25   37   36   
4113   

In [16]:
train_x=[]
train_y=[]
for i in range(15):
    x=rd2.iloc[:,i:i+9]
    x.columns=np.array(range(9))  
    y=rd2.iloc[:,i+9]
    y.columns=np.array(range(1))
    train_x.append(x)
    train_y.append(y)

In [17]:
train_x=pd.concat(train_x)
train_y=pd.concat(train_y)  #train_x and train_y are the type of Dataframe
train_x

0   1   2   3   4   5   6   7   8
9     26  39  36  35  31  28  25  20  19
27    21  23  30  30  22  18  13  13  11
45    19  25  27  20  16  14  15   8   4
63    27  27  14  20  22  24  26  33  48
81    80  80  76  81  75  66  70  65  66
99    66  55  46  46  46  42  35  35  40
117   41  32  35  31  33  25  36  28  33
135   48  53  60  60  52  47  45  50  43
153   18  15   9   9  14  15  20  16  23
171    6   7   7   0   0   1   1   7   7
189   25  21  25  24  23  18  20  14   7
207   48  56  62  52  40  32  37  31  34
225   10  10  10  13  18  16   7   5   2
243   29  23  21  21  30  26  26  26  23
261    9   4   8   5  14  11  13   4   9
279   24  16   7   7   6   5   2  17  15
297   27  25  22  23  22  22  23  11   2
315   17  26  25  24  10   7  11  16  19
333   64  52  36  41  46  48  38  21  11
351   61  59  60  48  53  60  66  53  55
369   30  32  36  29  16  10  23  27  33
387   22  20  13   8  15  13  22  19  23
405   31  26  17  13  18  29  22  21  23
423   22  27  22  31  32  35  25  14   7
441    6   6   4   4   0   0   0   2   2
459   13  22  29  21  21  14  16   6  11
477   46  44  38  36  23  19   7  21  20
495   32  35  25  13  12   7   7   6   7
513    4   6   0   0   0   7   7   5   7
531    0   0   4   4   8   9  13  10   4
...   ..  ..  ..  ..  ..  ..  ..  ..  ..
3789  39  32  17  19  27  41  45  41  40
3807  18  30  30  18  11  10  21  17  18
3825  16  26  33  33  37  26  21  18  24
3843   6   3   3  13  19  15   4   7  12
3861  34  54  69  66  59  36  33  18  11
3879  18  18  18  -1  -1  -1  -1  -1  -1
3897  19  19  19  12   3   6  11  11   8
3915  22  22  21  21  19  14   7   6  10
3933  71  69  38   9   9  14  20  18  13
3951  26  26  25  34  39  38  33  24  24
3969   1  18  30  33  15  10  10  16  20
3987  12   4  13  13  17   7   5   4  20
4005  32  38  36  35  27  24  21  26  34
4023   0  10  18  18  18  18  18  18  18
4041  13  11  18  28  33  37  30  19   7
4059  15  16  22  25  27  18  19  12  10
4077  34  35  36  40  31  35  37  35  34
4095   7  12  15  25  37  36  34  22  13
4113  33  40  40  32  30  30  34  37  37
4131  30  24  32  33  40  24  15   7  16
4149   7  13  17  17  11  20  29  33  19
4167  26  39  46  48  51  43  34  33  36
4185  23  19  21  29  38  37  33  21  24
4203  47  55  66  70  66  66  70  70  59
4221  21  17  24  23  18  23  21  27  14
4239   8  16  28  37  39  36  36  31  26
4257  12   6   4  11  11   5   0   6   6
4275  31  31  36  31  31  34  39  36  24
4293  21  21  19  19  25  19  11   0   7
4311   1   7  24  37  49  37  28  17  24

[3600 rows x 9 columns]

In [18]:
train_x=np.array(train_x,float)
train_y=np.array(train_y,float)
train_x

array([[26., 39., 36., ..., 25., 20., 19.],
       [21., 23., 30., ..., 13., 13., 11.],
       [19., 25., 27., ..., 15.,  8.,  4.],
       ...,
       [31., 31., 36., ..., 39., 36., 24.],
       [21., 21., 19., ..., 11.,  0.,  7.],
       [ 1.,  7., 24., ..., 28., 17., 24.]])

In [19]:
#add bias to train dataset
train_x=np.concatenate((np.ones((train_x.shape[0],1)),train_x),axis=1)
train_x

array([[ 1., 26., 39., ..., 25., 20., 19.],
       [ 1., 21., 23., ..., 13., 13., 11.],
       [ 1., 19., 25., ..., 15.,  8.,  4.],
       ...,
       [ 1., 31., 31., ..., 39., 36., 24.],
       [ 1., 21., 21., ..., 11.,  0.,  7.],
       [ 1.,  1.,  7., ..., 28., 17., 24.]])

In [21]:
w=np.zeros(len(train_x[0]))
lr=10
Iteration=10000
sum_gra=np.zeros(len(train_x[0]))  #define sum=0
for i in range(Iteration):
    y_new=np.dot(train_x,w)
    loss=y_new-train_y
    gra= 2*np.dot(train_x.transpose(),loss) #notice we must transpose train_x 
    sum_gra += gra**2
    ada=np.sqrt(sum_gra)
    w=w-lr*gra/ada
w    

array([ 2.15246702,  0.00728964, -0.04603067,  0.19941492, -0.20757788,
       -0.04384333,  0.46235285, -0.54329351,  0.01552538,  1.07716609])

In [22]:
rd_test=pd.read_csv('test.csv')
rd_test.head()

id_0 AMB_TEMP    15    14  14.1    13  13.1  13.2  13.3  13.4    12
0  id_0      CH4   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8
1  id_0       CO  0.36  0.35  0.34  0.33  0.33  0.34  0.34  0.37  0.42
2  id_0     NMHC  0.11  0.09  0.09   0.1   0.1   0.1   0.1  0.11  0.12
3  id_0       NO   0.6   0.4   0.3   0.3   0.3   0.7   0.8   0.8   0.9
4  id_0      NO2   9.3   7.1   6.1   5.7   5.5   5.3   5.5   7.1   7.5

In [24]:
rd2=rd_test[rd_test['AMB_TEMP']=='PM2.5']
rd2

id_0 AMB_TEMP   15   14 14.1   13 13.1 13.2 13.3 13.4   12
8       id_0    PM2.5   27   13   24   29   41   30   29   27   28
26      id_1    PM2.5   46   47   57   78   84   76   59   61   61
44      id_2    PM2.5   10   10   25   34   40   39   36   25   22
62      id_3    PM2.5   71   58   51   41   41   46   43   34   29
80      id_4    PM2.5   13   23   18   10    5    5   13    9   12
98      id_5    PM2.5   25   32   40   40   31   27   13   24   29
116     id_6    PM2.5   37   42   65   70   71   58   51   41   41
134     id_7    PM2.5   17   22   17    9   17   23   29   17   18
152     id_8    PM2.5   78   84   76   59   61   61   60   49   49
170     id_9    PM2.5   13   13   18   20   14    9   16   22   35
188    id_10    PM2.5   27   36   42   32   24   25   32   40   40
206    id_11    PM2.5   27   18   24   35   45   51   55   60   62
224    id_12    PM2.5   62   59   55   48   62   60   62   54   41
242    id_13    PM2.5   44   40   32   24   26   27   18   24   35
260    id_14    PM2.5   74   80   73   90   79   67   47   34   28
278    id_15    PM2.5   26   34   29   20   24   16   16   13   12
296    id_16    PM2.5   28   33   27   37   42   65   70   71   58
314    id_17    PM2.5   60   49   49   38   41   30   23   19   20
332    id_18    PM2.5   22   20   20   14   12   16   13   16   16
350    id_19    PM2.5   30   17   10    5   13   13   13   13   18
368    id_20    PM2.5    9    1    4    3    1    4    7   15   14
386    id_21    PM2.5   31   24   17    1    9   23   25   29   25
404    id_22    PM2.5   54   47   41   39   37   28   28   34   38
422    id_23    PM2.5   83   83   85   65   47   30   20   13    7
440    id_24    PM2.5   39   57   63   54   45   39   49   55   62
458    id_25    PM2.5   14   14    6    4    6   16   31   36   48
476    id_26    PM2.5   12   16   24   17    8   11   19   30   29
494    id_27    PM2.5   11   19   30   29   26   16   14    9    9
512    id_28    PM2.5   17    1    9   23   25   29   25   31   29
530    id_29    PM2.5   18   14   14    6    4    6   16   31   36
...      ...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
3788  id_210    PM2.5   62   34   32   35   36   25   31   30   34
3806  id_211    PM2.5   49   66   93  106  111   96   84   79   75
3824  id_212    PM2.5   11   11   11   15   20   25   31   26   24
3842  id_213    PM2.5  183  159  142  121  137  152  165  154  131
3860  id_214    PM2.5    5    1    6   11    9   18   21   35   39
3878  id_215    PM2.5   31   43  102  102  136  120  118   94   89
3896  id_216    PM2.5   36   25   31   30   34   40   49   66   93
3914  id_217    PM2.5   48   60   68   63   71   63   65   62   73
3932  id_218    PM2.5   24   14    8    0    4   19   34   42   33
3950  id_219    PM2.5   62   73   88   88   70   57   52   44   24
3968  id_220    PM2.5   25   37   41   43   49   50   43   40   31
3986  id_221    PM2.5   56   72   69   65   71   87   82   74   57
4004  id_222    PM2.5   26   32   37   29   27   23   26   24   29
4022  id_223    PM2.5    2    0    9   24   44   33   39   29   45
4040  id_224    PM2.5   65   64   62   50   45   47   56   57   49
4058  id_225    PM2.5   29   16   13    2    0    4    4    9    5
4076  id_226    PM2.5   33   39   29   45   27   24   10   10    3
4094  id_227    PM2.5   18   20   27   39   41   37   42   56   72
4112  id_228    PM2.5   33   29   17   11   13   24   23   27   26
4130  id_229    PM2.5    6   10   11   13    5    3    0    0    0
4148  id_230    PM2.5   -1   28   41   39   45   39   37   39   39
4166  id_231    PM2.5   13    9   15   20   26   23   18   11   14
4184  id_232    PM2.5   15   20   26   23   18   11   14   11   22
4202  id_233    PM2.5   43   40   31   29   16   13    2    0    4
4220  id_234    PM2.5    0    7   16   16   17   17   28   22   17
4238  id_235    PM2.5    7   13    6   12    5    6    6   14   21
4256  id_236    PM2.5    2    0    4    4    9    5   13    9   15
4274  id_237    PM2.5   16   25   12    8    7   11   1

In [25]:
PMdata_test=rd2.iloc[:,2:]
PMdata_test

15   14 14.1   13 13.1 13.2 13.3 13.4   12
8      27   13   24   29   41   30   29   27   28
26     46   47   57   78   84   76   59   61   61
44     10   10   25   34   40   39   36   25   22
62     71   58   51   41   41   46   43   34   29
80     13   23   18   10    5    5   13    9   12
98     25   32   40   40   31   27   13   24   29
116    37   42   65   70   71   58   51   41   41
134    17   22   17    9   17   23   29   17   18
152    78   84   76   59   61   61   60   49   49
170    13   13   18   20   14    9   16   22   35
188    27   36   42   32   24   25   32   40   40
206    27   18   24   35   45   51   55   60   62
224    62   59   55   48   62   60   62   54   41
242    44   40   32   24   26   27   18   24   35
260    74   80   73   90   79   67   47   34   28
278    26   34   29   20   24   16   16   13   12
296    28   33   27   37   42   65   70   71   58
314    60   49   49   38   41   30   23   19   20
332    22   20   20   14   12   16   13   16   16
350    30   17   10    5   13   13   13   13   18
368     9    1    4    3    1    4    7   15   14
386    31   24   17    1    9   23   25   29   25
404    54   47   41   39   37   28   28   34   38
422    83   83   85   65   47   30   20   13    7
440    39   57   63   54   45   39   49   55   62
458    14   14    6    4    6   16   31   36   48
476    12   16   24   17    8   11   19   30   29
494    11   19   30   29   26   16   14    9    9
512    17    1    9   23   25   29   25   31   29
530    18   14   14    6    4    6   16   31   36
...   ...  ...  ...  ...  ...  ...  ...  ...  ...
3788   62   34   32   35   36   25   31   30   34
3806   49   66   93  106  111   96   84   79   75
3824   11   11   11   15   20   25   31   26   24
3842  183  159  142  121  137  152  165  154  131
3860    5    1    6   11    9   18   21   35   39
3878   31   43  102  102  136  120  118   94   89
3896   36   25   31   30   34   40   49   66   93
3914   48   60   68   63   71   63   65   62   73
3932   24   14    8    0    4   19   34   42   33
3950   62   73   88   88   70   57   52   44   24
3968   25   37   41   43   49   50   43   40   31
3986   56   72   69   65   71   87   82   74   57
4004   26   32   37   29   27   23   26   24   29
4022    2    0    9   24   44   33   39   29   45
4040   65   64   62   50   45   47   56   57   49
4058   29   16   13    2    0    4    4    9    5
4076   33   39   29   45   27   24   10   10    3
4094   18   20   27   39   41   37   42   56   72
4112   33   29   17   11   13   24   23   27   26
4130    6   10   11   13    5    3    0    0    0
4148   -1   28   41   39   45   39   37   39   39
4166   13    9   15   20   26   23   18   11   14
4184   15   20   26   23   18   11   14   11   22
4202   43   40   31   29   16   13    2    0    4
4220    0    7   16   16   17   17   28   22   17
4238    7   13    6   12    5    6    6   14   21
4256    2    0    4    4    9    5   13    9   15
4274   16   25   12    8    7   11   11    3    0
4292   29   27   23   26   24   29   35   35   26
4310   12    8    7   11   11    3    0    0    0

[240 rows x 9 columns]

In [26]:
test_x=np.array(PMdata_test,float)
test_x

array([[27., 13., 24., ..., 29., 27., 28.],
       [46., 47., 57., ..., 59., 61., 61.],
       [10., 10., 25., ..., 36., 25., 22.],
       ...,
       [16., 25., 12., ..., 11.,  3.,  0.],
       [29., 27., 23., ..., 35., 35., 26.],
       [12.,  8.,  7., ...,  0.,  0.,  0.]])

In [27]:
test_x=np.concatenate((np.ones((test_x.shape[0],1)),test_x),axis=1)
test_x

array([[ 1., 27., 13., ..., 29., 27., 28.],
       [ 1., 46., 47., ..., 59., 61., 61.],
       [ 1., 10., 10., ..., 36., 25., 22.],
       ...,
       [ 1., 16., 25., ..., 11.,  3.,  0.],
       [ 1., 29., 27., ..., 35., 35., 26.],
       [ 1., 12.,  8., ...,  0.,  0.,  0.]])

In [28]:
y_pre=np.dot(test_x,w)
y_pre

array([ 27.41442114,  61.55576434,  20.49803196,  29.53443361,
        10.79767011,  36.20720196,  39.7163839 ,  16.57175712,
        48.23627374,  33.98378897,  39.25396544,  58.48319052,
        37.23356467,  41.66913212,  27.55246309,  13.1889624 ,
        52.30029122,  23.63327639,  19.7662073 ,  20.51352232,
        15.66268864,  28.49276165,  38.03477309,  11.08073866,
        58.24257196,  44.53164349,  28.87672212,   9.80659247,
        29.69971845,  36.35090639,  19.43428788,  12.71486259,
        17.0117771 ,   8.62668932,  18.82222166,  38.66455325,
        20.08402335,  28.39280922,   6.94419602,  59.68906378,
        46.63323825,  17.28591502,  49.70855984,  18.98558771,
        44.15939046,  51.19898476,  61.64642457,  40.29588702,
        51.04026409,  42.08154294,  30.7565433 ,  25.43723702,
        41.07801634,  26.36300435,  38.24278214,  39.90044155,
        25.70020226,  22.49555053,  37.45505336,  31.50166898,
        15.99339805,  23.13494156,  31.72293469,  55.05

In [29]:
y_submit=pd.read_csv('sampleSubmission.csv')
y_submit.value=y_pre   #get value by .value   automatically identify numbers
y_submit.to_csv('sampleSubmission.csv',index=False)

In [30]:
real=pd.read_csv('answer.csv')
error=abs(y_submit.value-real.value).sum()/len(real.value)
error

4.97442948413227